MERGE INTO sys_dept (id, parent_id, dept_name, leader, phone, sort, status, create_time, update_time)
VALUES (1, 0, '纪委监察委', '系统管理员', '010-00000000', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- admin123 BCrypt hash (generated by BCryptPasswordEncoder)
MERGE INTO sys_user (id, username, password, real_name, phone, email, dept_id, status, deleted, last_login_time, create_time, update_time)
VALUES (1, 'admin', '$2a$10$2N9itqPJiUyzXYn1YOnqQeXrJS37nnItDEUxKuDOA3VSdZ0WYfqNC', '系统管理员', null, null, 1, 1, 0, null, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

MERGE INTO sys_role (id, role_name, role_code, description, status, deleted, create_time, update_time)
VALUES (1, '超级管理员', 'SUPER_ADMIN', '系统最高权限', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

MERGE INTO sys_user_role (id, user_id, role_id) VALUES (1, 1, 1);

MERGE INTO sys_menu (id, parent_id, name, path, component, perms, type, icon, sort_order, sort, visible, status, deleted, create_time, update_time)
VALUES (1, 0, '系统管理', '/system', 'Layout', 'system', 0, 'Setting', 1, 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

MERGE INTO sys_menu (id, parent_id, name, path, component, perms, type, icon, sort_order, sort, visible, status, deleted, create_time, update_time)
VALUES (2, 1, '用户管理', '/system/user', 'system/User', 'system:user:list', 1, 'User', 2, 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

MERGE INTO sys_menu (id, parent_id, name, path, component, perms, type, icon, sort_order, sort, visible, status, deleted, create_time, update_time)
VALUES (3, 1, '角色管理', '/system/role', 'system/Role', 'system:role:list', 1, 'Lock', 3, 2, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

MERGE INTO sys_menu (id, parent_id, name, path, component, perms, type, icon, sort_order, sort, visible, status, deleted, create_time, update_time)
VALUES (4, 1, '菜单管理', '/system/menu', 'system/Menu', 'system:menu:list', 1, 'Menu', 4, 3, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

MERGE INTO sys_role_menu (id, role_id, menu_id) VALUES (1, 1, 1);
MERGE INTO sys_role_menu (id, role_id, menu_id) VALUES (2, 1, 2);
MERGE INTO sys_role_menu (id, role_id, menu_id) VALUES (3, 1, 3);
MERGE INTO sys_role_menu (id, role_id, menu_id) VALUES (4, 1, 4);

MERGE INTO sys_classification_level (id, level_code, level_name, level_order, description, status, create_time, update_time)
VALUES (1, 'PUBLIC', '公开', 5, '可对外公开', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

MERGE INTO sys_classification_level (id, level_code, level_name, level_order, description, status, create_time, update_time)
VALUES (2, 'INTERNAL', '内部', 4, '仅限内部使用', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

MERGE INTO sys_classification_level (id, level_code, level_name, level_order, description, status, create_time, update_time)
VALUES (3, 'SECRET', '秘密', 3, '一般涉密信息', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

MERGE INTO sys_classification_level (id, level_code, level_name, level_order, description, status, create_time, update_time)
VALUES (4, 'CONFIDENTIAL', '机密', 2, '重要涉密信息', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

MERGE INTO sys_classification_level (id, level_code, level_name, level_order, description, status, create_time, update_time)
VALUES (5, 'TOP_SECRET', '绝密', 1, '核心涉密信息', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
