import { test, expect } from './fixtures'
import { login, waitForApiResponse, generateTestCode, clearAuth } from './utils'

test.describe('TC-CASE Case Management Module (P0)', () => {

  test.beforeEach(async ({ page }) => {
    await login(page)
    // Navigate to case management
    await page.goto('/case')
    await page.waitForSelector('.el-table', { timeout: 10000 })
  })

  test('TC-CASE-01: Case list renders with search bar and table', async ({ page }) => {
    // Verify search form elements
    await expect(page.getByPlaceholder('请输入案件编号')).toBeVisible()
    await expect(page.getByPlaceholder('请输入案件名称')).toBeVisible()
    await expect(page.locator('.search-form')).toBeVisible()
    // Verify toolbar with add button
    await expect(page.getByRole('button', { name: '新增案件' })).toBeVisible()
    // Verify table renders
    await expect(page.locator('.el-table')).toBeVisible()
    // Verify table columns
    await expect(page.locator('.el-table')).toContainText('案件编号')
    await expect(page.locator('.el-table')).toContainText('案件名称')
    await expect(page.locator('.el-table')).toContainText('案件类型')
    await expect(page.locator('.el-table')).toContainText('被调查人')
    await expect(page.locator('.el-table')).toContainText('状态')
    // Verify pagination
    await expect(page.locator('.el-pagination')).toBeVisible()
  })

  test('TC-CASE-02: Create new case with full form', async ({ page }) => {
    const testCode = generateTestCode('E2E')
    const testName = `E2E测试案件 ${Date.now()}`

    // Click add button
    await page.getByRole('button', { name: '新增案件' }).click()
    // Wait for dialog to appear
    await expect(page.locator('.el-dialog')).toBeVisible()
    await expect(page.locator('.el-dialog__title')).toContainText('新增案件')

    // Fill the form
    await page.getByPlaceholder('请输入案件编号').fill(testCode)
    await page.getByPlaceholder('请输入案件名称').first().fill(testName)

    // Select case type
    await page.locator('.el-select').filter({ hasText: '案件类型' }).click()
    await page.getByRole('option', { name: '违纪' }).click()

    // Select status (defaults to 草稿)
    await page.locator('.el-select').filter({ hasText: '状态' }).click()
    await page.getByRole('option', { name: '草稿' }).click()

    // Fill respondent
    await page.getByPlaceholder('请输入被调查人姓名').first().fill('张三')
    await page.getByPlaceholder('请输入承办部门').fill('第一纪检监察室')
    await page.getByPlaceholder('请输入承办人').fill('李四')

    // Set filing date
    await page.locator('input[placeholder="请选择立案日期"]').click()
    // Pick today's date from the date picker
    await page.locator('.el-date-picker__header-label').click()
    await page.locator('.el-date-table td').filter({ hasText: '15' }).first().click()

    // Fill description
    await page.getByPlaceholder('请输入案件描述').fill('E2E自动化测试案件')
    await page.getByPlaceholder('请输入备注').fill('测试备注')

    // Wait for API response and submit
    const [response] = await Promise.all([
      page.waitForResponse((res) => res.url().includes('/api/case') && res.request().method() === 'POST'),
      page.getByRole('button', { name: '保存' }).click(),
    ])

    const resJson = await response.json()
    expect(resJson.code).toBe(200)

    // Verify success message
    await expect(page.locator('.el-message--success')).toContainText('新增成功')

    // Verify the new case appears in the table
    await expect(page.locator('.el-table')).toContainText(testCode)
    await expect(page.locator('.el-table')).toContainText(testName)
  })

  test('TC-CASE-03: Required field validation', async ({ page }) => {
    // Click add button
    await page.getByRole('button', { name: '新增案件' }).click()
    await expect(page.locator('.el-dialog')).toBeVisible()

    // Try to save without filling required fields
    await page.getByRole('button', { name: '保存' }).click()

    // Wait a moment for validation messages
    await page.waitForTimeout(500)

    // Verify required field error messages appear
    const errorMsgs = page.locator('.el-form-item__error')
    await expect(errorMsgs.first()).toBeVisible()

    // Verify specific required field messages
    await expect(page.locator('.el-form-item__error')).toContainText('请输入案件编号')
    await expect(page.locator('.el-form-item__error')).toContainText('请输入案件名称')
    await expect(page.locator('.el-form-item__error')).toContainText('请选择案件类型')
    await expect(page.locator('.el-form-item__error')).toContainText('请输入被调查人')
  })

  test('TC-CASE-04: Auto-generated case number', async ({ page }) => {
    // Click add button
    await page.getByRole('button', { name: '新增案件' }).click()
    await expect(page.locator('.el-dialog')).toBeVisible()

    // The case number field should be empty by default (auto-generated by backend)
    const caseCodeInput = page.getByPlaceholder('请输入案件编号')
    const initialValue = await caseCodeInput.inputValue()
    expect(initialValue).toBe('')

    // We can provide our own case code (the field is editable)
    const customCode = generateTestCode('AUTO')
    await caseCodeInput.fill(customCode)
    const enteredValue = await caseCodeInput.inputValue()
    expect(enteredValue).toBe(customCode)

    // The backend should accept it — fill minimal required fields and save
    await page.getByPlaceholder('请输入案件名称').first().fill(`Auto Test ${Date.now()}`)
    await page.locator('.el-select').filter({ hasText: '案件类型' }).click()
    await page.getByRole('option', { name: '违纪' }).click()
    await page.getByPlaceholder('请输入被调查人姓名').first().fill('测试人')

    await page.getByRole('button', { name: '保存' }).click()

    // Verify success
    await expect(page.locator('.el-message--success')).toContainText('新增成功')
    // Verify case appears in table
    await expect(page.locator('.el-table')).toContainText(customCode)
  })

  test('TC-CASE-05: Search by case number', async ({ page }) => {
    // First create a test case to search for
    const searchCode = generateTestCode('SEARCH')

    await page.getByRole('button', { name: '新增案件' }).click()
    await page.getByPlaceholder('请输入案件编号').fill(searchCode)
    await page.getByPlaceholder('请输入案件名称').first().fill(`Search Test ${Date.now()}`)
    await page.locator('.el-select').filter({ hasText: '案件类型' }).click()
    await page.getByRole('option', { name: '违纪' }).click()
    await page.getByPlaceholder('请输入被调查人姓名').first().fill('搜索测试')

    await page.getByRole('button', { name: '保存' }).click()
    await expect(page.locator('.el-message--success')).toContainText('新增成功')

    // Now search by case number
    await page.getByPlaceholder('请输入案件编号').fill(searchCode)
    await page.getByRole('button', { name: '查询' }).click()
    await page.waitForTimeout(1000)

    // Verify the case appears in results
    await expect(page.locator('.el-table')).toContainText(searchCode)
  })

  test('TC-CASE-06: Search by case name', async ({ page }) => {
    // First create a test case with a unique name
    const searchName = `NameSearch_${Date.now()}`

    await page.getByRole('button', { name: '新增案件' }).click()
    await page.getByPlaceholder('请输入案件编号').fill(generateTestCode('NSE'))
    await page.getByPlaceholder('请输入案件名称').first().fill(searchName)
    await page.locator('.el-select').filter({ hasText: '案件类型' }).click()
    await page.getByRole('option', { name: '违法' }).click()
    await page.getByPlaceholder('请输入被调查人姓名').first().fill('名称搜索')

    await page.getByRole('button', { name: '保存' }).click()
    await expect(page.locator('.el-message--success')).toContainText('新增成功')

    // Now search by case name
    await page.getByPlaceholder('请输入案件名称').fill(searchName)
    await page.getByRole('button', { name: '查询' }).click()
    await page.waitForTimeout(1000)

    // Verify the case appears in results
    await expect(page.locator('.el-table')).toContainText(searchName)
  })
})
